# Generated by Django 5.1.6 on 2025-04-15 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('role', models.CharField(choices=[('freelancer', 'Client'), ('client', 'Client')], max_length=20)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('method', models.CharField(max_length=50)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.project'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField()),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.contract')),
                ('reviewed_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='freelanceApp.user')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='freelanceApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='freelanceApp.user'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.contract')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='freelanceApp.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='freelanceApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skills', models.CharField(max_length=500)),
                ('portfolio', models.TextField(blank=True)),
                ('Experience', models.TextField(blank=True)),
                ('certifications', models.FileField(upload_to='certificates')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('job_success_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('freelancer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_client', to='freelanceApp.user'),
        ),
        migrations.AddField(
            model_name='contract',
            name='freelancer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_freelancer', to='freelanceApp.user'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=100)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hiring_history', models.TextField(blank=True)),
                ('reviews_given', models.PositiveIntegerField(default=0)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.project')),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='freelanceApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('withdrawal_preferences', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.skill')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.user')),
            ],
        ),
    ]
