# Generated by Django 5.1.6 on 2025-04-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceApp', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pfp/'),
        ),
    ]
