# Generated by Django 5.1.6 on 2025-04-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceApp', '0005_alter_profile_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], max_length=20)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='pfp/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='freelancer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_client', to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='freelancer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_freelancer', to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='freelancer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='freelanceApp.user'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.user'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
