# Generated by Django 5.1.6 on 2025-04-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceApp', '0006_user_alter_bankdetails_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pfp',
        ),
    ]
