# Generated by Django 5.1.6 on 2025-04-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceApp', '0007_remove_user_pfp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='user_id',
            new_name='Userr_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewed_user_id',
            new_name='reviewed_Userr_id',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Userr',
        ),
        migrations.CreateModel(
            name='UserrSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.userr')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelanceApp.skill')),
            ],
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
