# Generated by Django 5.1.6 on 2025-04-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanceApp', '0008_rename_user_id_bankdetails_userr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userr',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pfp/'),
        ),
    ]
